--
--  Monad.agda - Monads generated by dependent polynomials
--

open import Cubical.Foundations.Prelude

open import TyStr
open import DepPoly

module Monad where

  record Monad (𝕋 : TyStr) : Type₁ where
    field
      P : DepPoly 𝕋 𝕋
      μ : P ⊚ P ⇒ P
      η : IdPoly 𝕋 ⇒ P

  open Monad

  assoc-mult-left : {𝕋 : TyStr} (M : Monad 𝕋)
    → (Γ : Ctx 𝕋) (A : Ty 𝕋) 
    → (t : Tm ((P M ⊚ P M) ⊚ P M) Γ A)
    → Tm (P M) Γ A 
  assoc-mult-left M Γ A (Δ , σ , t) =
    Tm⇒ (μ M) (Δ , Subst⇒ (μ M) σ , t)

  assoc-mult-right : {𝕋 : TyStr} (M : Monad 𝕋)
    → (Γ : Ctx 𝕋) (A : Ty 𝕋) 
    → (t : Tm (P M ⊚ (P M ⊚ P M)) Γ A)
    → Tm (P M) Γ A 
  assoc-mult-right M Γ A (Δ , σ , Θ , τ , t) =
    Tm⇒ (μ M) (Δ , σ , Tm⇒ (μ M) (Θ , τ , t)) 

  unit-mult-left : {𝕋 : TyStr} (M : Monad 𝕋)
    → (Γ : Ctx 𝕋) (A : Ty 𝕋) (t : Tm (P M) Γ A)
    → Tm (P M) Γ A
  unit-mult-left M Γ A t =
    Tm⇒ (μ M) (Γ , Subst⇒ (η M) (idSubst Γ) , t)

  unit-mult-right : {𝕋 : TyStr} (M : Monad 𝕋)
    → (Γ : Ctx 𝕋) (A : Ty 𝕋) (t : Tm (P M) Γ A)
    → Tm (P M) Γ A
  unit-mult-right M Γ A t = 
    Tm⇒ (μ M) (A ► ϵ , tmToSubst t , Tm⇒ (η M) (idT A))




    -- this probably needs to take substitutions instead of terms
  record SubStr {𝕋 : TyStr} (M : Monad 𝕋) : Type₁ where
    coinductive
    field
      SubStrCtx : {Γ : Ctx 𝕋} {T : Ty 𝕋} (T' : Ty (𝕋 // T)) (t : Tm (P M) Γ T) 
        →  Ty ((CtxStr 𝕋) // Γ)
      SubStrTm : {Γ : Ctx 𝕋} {T : Ty 𝕋} (T' : Ty (𝕋 // T)) (t : Tm (P M) Γ T)  
        → Tm (⇑ (P M) t) (SubStrCtx T' t) T'
      SubLift : {Γ Δ : Ctx 𝕋} {T : Ty 𝕋} (T' : Ty (𝕋 // T)) (t : Tm (P M) Γ T) 
        → (σ : Subst (P M) Δ Γ) → (Δ' : Ty ((CtxStr 𝕋) // Δ)) 
        → (t' : Tm (⇑ (P M) (Tm⇒ (μ M) (Γ , σ , t))) Δ' T')
        → Subst ⌈ σ ⌉s Δ' (SubStrCtx T' t)
      LiftEq : {Γ Δ : Ctx 𝕋} {T : Ty 𝕋} (T' : Ty (𝕋 // T)) (t : Tm (P M) Γ T) 
        → (σ : Subst (P M) Δ Γ) → (Δ' : Ty ((CtxStr 𝕋) // Δ)) 
        → (t' : Tm (⇑ (P M) (Tm⇒ (μ M) (Γ , σ , t))) Δ' T')
        → t' ≡ Tm⇒ (⇑⇒ (μ M) (Γ , σ , t)) ((SubStrCtx T' t) , ((SubLift T' t σ Δ' t') , SubStrTm T' t))

  -- the substitution cant be empty!
  record SubStrSub {𝕋 : TyStr} (M : Monad 𝕋) : Type₁ where
    field
      S : SubStr M -- needed since we lif the morphism in SubLiftSub and therefore Sublift is not the same operation
      SubStrSubCtx : {Γ Δ : Ctx 𝕋} (T' : Ty ⌈ Δ ⌉) (Γ' : Ctx ⌈ Γ ⌉) (σ : Subst (P M) Γ Δ) (t : Tm ⌈ σ ⌉s Γ' T') (T'' : Ty (⌈ Δ ⌉ // T'))
        → Ty (((CtxStr 𝕋) // Γ) // Γ')
      SubStrSubTm : {Γ Δ : Ctx 𝕋} (T' : Ty ⌈ Δ ⌉) (Γ' : Ctx ⌈ Γ ⌉) (σ : Subst (P M) Γ Δ) (t : Tm ⌈ σ ⌉s Γ' T') (T'' : Ty (⌈ Δ ⌉ // T'))
        → Tm (⇑ ⌈ σ ⌉s t) (SubStrSubCtx T' Γ' σ t T'') T''
      SubLiftSub : {Γ Φ Δ : Ctx 𝕋} (T' : Ty ⌈ Δ ⌉) (Γ' : Ctx ⌈ Γ ⌉) (σ : Subst (P M) Γ Δ) (t : Tm ⌈ σ ⌉s Γ' T') (T'' : Ty (⌈ Δ ⌉ // T'))
        → (φ : Subst (P M) Φ Γ) → (Φ' : Ty ((CtxStr 𝕋) // Φ)) → (φ' : Subst ⌈ φ ⌉s Φ' Γ')
        → Tm (⇑ ⌈ Subst⇒ (μ M) (SubComp φ σ) ⌉s (Tm⇒ ⌈ (μ M) ∣ (SubComp φ σ) ⌉⇒ {Γ = Φ'} {T = T'} {! Γ' , φ' , t  !})) {!   !} {!   !} -- Tm (⇑ ⌈ Subst⇒ (μ M) (SubComp φ σ) ⌉s

  -- Tm⇒ ⌈ (μ M) ∣ (SubComp φ σ) ⌉⇒
  -- record WkStrM {𝕋 : TyStr} (M : Monad 𝕋) : Type₁ where
  --   coinductive
  --   field

  record SubMonad (𝕋 : TyStr) : Type₁ where
    coinductive
    field
      M : Monad 𝕋
      S : SubStr M
      SubUnique : (S' : SubStr (M)) → S' ≡ S

      
        
  
   