--
--  Monad.agda - Monads generated by dependent polynomials
--

open import MiniHoTT

open import TyStr
open import DepPoly

module Monad where

  record Monad (𝕋 : TyStr) : Type₁ where
    field
      P : DepPoly 𝕋 𝕋
      μ : P ⊚ P ⇒ P
      η : IdPoly 𝕋 ⇒ P

